### ISSUE TITLE
Enable APIResponse auto-generation with annotations present

### ISSUE THREAD

**Issue by neon-dev** [smallrye/smallrye-open-api#100]
Methods returning a specific object type (with the exception of JAX-RS `Response`) do not need `@APIResponse` because of the auto detection, which is very handy.
Unfortunately you often cannot use that feature for some (most?) JAX-RS implementations. Because if you return `null`, RESTeasy for example returns 204 No Content and this cannot be declared without needing to also declare the `@APIResponse` for 200.

This is because the current logic does not auto generate anything if there is any explicitly defined `@APIResponse` annotation present:
https://github.com/smallrye/smallrye-open-api/blob/8e05eeb79e800312da9ef49b1a6821424bb069a4/implementation/src/main/java/io/smallrye/openapi/runtime/scanner/OpenApiAnnotationScanner.java#L627

There are multiple ways this could be changed:
1. Auto generate default responses if the respective `responseCode` (200 for non-void methods, 201/204 for void methods) has not been explicitly defined. Although you then cannot disable them you can still override them.
2. Auto generate default responses if an empty `@APIResponse` annotation is present.
3. Introduce a new annotation or option to recognize that a methods return value is nullable. Then the auto generation can add a 204 response addtional to the 200.

**Comment by cghislai** [comment]
I hit this bug when trying to specify a response header for a resource returning a pojo array - see https://github.com/eclipse/microprofile-open-api/issues/362 for details.

I think a response schema should be generated if not explicitly overridden with the `@ApiResponse#content` parameter. For my use case, I only intended to add a specific header documentation, but then got stuck because there was no way to correctly specify the (response body) array schema.

More broadly, I think response generation could be broken down more further, allowing to override only part of it if required. This seems tricky, as it seems not intuitive how one could overwrite the default versus amend it.
There could be some implicit treatment, like the first `@ApiResponse` of an `@ApiResponses` annotation is the default one. If that annotation is empty, it is autogenerated. If parts of that annotation are missing, they are generated. If it is absent (`@ApiResponses` is empty), nothing gets generated. This is like suggestions #1 and #2 from the OP.

**Comment by MikeEdgar** [comment]
+1 to supporting a generated `content` if not specified in a method's `@ApiResponse`. However, I believe this issue is dealing with auto-generating additional status codes (`@ApiResponse(responseCode = "...")`

**Comment by neon-dev** [comment]
You are right @MikeEdgar, this issue was created because defining an additional response clears the auto generated one. But the issue @cghislai describes is closely related and the proposed override logic would greatly reduce the impact of this issue here. Because then adding a `@ApiResponse(responseCode = 200)` would in fact be enough to add back the missing default auto generated response. So @cghislai's proposal is way more useful and should help in more scenarios than what I described in this issue.
The common scheme of all suggestions here is to introduce an extension behavior instead of a hard replacement one. So ideally we should only have to write the absolute essential info which the auto generation does not already cover. And of course the necessary overrides in case something doesn't fit.

**Comment by MikeEdgar** [comment]
I think generating `content` if missing from `@ApiResponse` is a great idea. I hesitate a bit regarding adding response codes if the application has already provided them - particularly because there is no way to remove them other than with a filter.
@cghislai , @neon-dev  - would you mind giving some example annotated methods and expected results for the cases you're thinking about?

**Comment by cghislai** [comment]
For my use case, in this example:
<details>
  <summary>Pet resource</summary>
 <pre>

```java
@Path("/pet")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public interface PetResource {

    @GET
    @Path("/a")
    @APIResponses(value = {
            @APIResponse(
                    headers = @Header(
                            name = "X-Custom-Header",
                            schema = @Schema(type = SchemaType.STRING)
                    )
            )
    })
    List<Pet> getPetsA();

    @GET
    @Path("/b")
    @APIResponses(value = {
            @APIResponse(
                    responseCode = "200",
                    headers = @Header(
                            name = "X-Custom-Header",
                            schema = @Schema(type = SchemaType.STRING)
                    )
            )
    })
    List<Pet> getPetsB();

    @GET
    @Path("/c")
    @APIResponses(value = {
            @APIResponse(
                    responseCode = "200",
                    headers = @Header(
                            name = "X-Custom-Header",
                            schema = @Schema(type = SchemaType.STRING)
                    ),
                    content = @Content(
                            schema = @Schema(
                                    type = SchemaType.ARRAY,
                                    implementation = Pet.class
                            )
                    ),
                    description = "OK"
            )
    })
    List<Pet> getPetsC();

    @GET
    @Path("/d")
    List<Pet> getPetsD();

```
</pre>
</details>

I was expecting the same output for the /a, /b and /c endpoints:
<details>
  <summary>get /pet /c</summary>
 <pre>

```yaml

/pet/c:
    get:
      responses:
        200:
          description: OK
          headers:
            X-Custom-Header:
              style: simple
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

```
</pre>
</details>

Just overriding the default response generated:
<details>
  <summary>get /pet/d</summary>
 <pre>

```yaml

  /pet/d:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

```
</pre>
</details>

As for how to differentiate when one wants to overwrite the generated response, I was suggesting that such resources mehods:
<details>
  <summary>Pet resource e-f</summary>
 <pre>

```java


    @GET
    @Path("/d")
    List<Pet> getPetsD();

   @GET
    @Path("/e")
    @APIResponses(value = {
            @APIResponse(),
            @APIResponse(
                    responseCode = "400",
                    headers = @Header(
                            name = "X-Custom-Error-Header",
                            schema = @Schema(type = SchemaType.STRING)
                    )
            )
    })
    List<Pet> getPetsE();

    @GET
    @Path("/f")
    @APIResponses(value = {
            @APIResponse(
                    responseCode = "400",
                    headers = @Header(
                            name = "X-Custom-Error-Header",
                            schema = @Schema(type = SchemaType.STRING)
                    )
            )
    })
    List<Pet> getPetsF();
```
</pre>
</details>

Would generate this yaml:
<details>
  <summary>get /pet/e /f</summary>
 <pre>

```yaml

  /pet/d:
    get:
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
  /pet/e:
    get:
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        400:
          headers:
            X-Custom-Error-Header:
              style: simple
              schema:
                type: string
  /pet/f:
    get:
      responses:
        400:
          headers:
            X-Custom-Error-Header:
              style: simple
              schema:
                type: string

```
</pre>
</details>
I wasn't sure it would be intuitive.
Note that in the absence of annotation, the 'default' return code case would be generated, so that there would be no need to guess the 20X cases that the jax-rs implementations could return by default.

**Comment by MikeEdgar** [comment]
Thank you for the examples, that really helps. Now for a few additional questions.
1. @neon-dev , what would you do to address your original problem where you're looking for both a `200` and `204` response? Would you use `@ApiResponse(responseCode = "204")` and then also use an empty `@ApiResponse` and expect the `default` entry to be generated with what was previously located in the default `200` entry?
2. Does it make sense to include the default description in responses other than the default one? The "OK" description on the `400` status in example "f" seems off. My take would be to only use the generated defaults when (a) the `responseCode` is "default" or (b) for other `responseCode`s where the `content` is not specified.
3. Do you expect the schema of the method's return type to be used for all `@ApiResponse` annotations or only the one with `responseCode = "default"` (either implicit or explicit)?

**Comment by cghislai** [comment]
I understand that smallrye would generate a response in the absence of any
@ApiResponse, or for those with responseCode="default". With that in mind:

2. The description field is required in the yaml document. Maybe using
another description like "Default response" would be better to produce
valid output in the absence of any annotation.
3. I would restrict auto generation to the minimum required to document the
jax rs behaviour, so a). If one wants to list possible error codes, i dont
see the need to generate a response body that would probably be incorrect.



Le mar. 16 juil. 2019 03:07, Michael Edgar <notifications@github.com> a
écrit :

**Comment by neon-dev** [comment]
@MikeEdgar as for your first question:
I would actually write `@ApiResponse(responseCode = 200)`. This should work exactly like defining an empty `@ApiResponse` (just like in @cghislai's example for `get /pet/e`) but generate it as "200" instead of "default" in the openapi yaml file.
So I'd expect the underlying logic to always try to infer missing info from the method and complete it automatically. In case something doesn't fit, we would override the annotation property.

Here's an example to make it more clear:
```java
@GET
@Path("/g")
List<Pet> getPetsG();

@GET
@Path("/h")
@APIResponse(responseCode = "200")
@APIResponse(responseCode = "204")
List<Pet> getPetsH();

@GET
@Path("/i")
@APIResponse(responseCode = "204")
List<Pet> getPetsI();
```

```yml
/pet/g:
  get:
    responses:
      default:
        description: OK
        content:
          application/json:
            schema:
            type: array
            items:
              $ref: '#/components/schemas/Pet'
/pet/h:
  get:
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
            type: array
            items:
              $ref: '#/components/schemas/Pet'
      204:
/pet/i:
  get:
    responses:
      204:
```

Note that 204 should not auto generate content, because 204 by [spec should never return content](https://tools.ietf.org/html/rfc7231#section-6.3.5):
> A 204 response is terminated by the first empty line after the header fields because it cannot contain a message body.

**Comment by MikeEdgar** [comment]
Based on a previous comment here and [the OpenAPI response spec](https://swagger.io/specification/#responsesObject), I think the `204` entries need at least a `description`.

Reading the description of the `default` response, I think using it in auto generation might be a misuse. My reading of that field's purpose is that it should be used to document responses that are out of the norm or otherwise undeclared (think of a JAX-RS exception handler that is only related to the resource method by the type of exception that it catches and responds for). I think that a method's return type in association with the HTTP method effectively "declare" the response (i.e. the `200`, `201`, and `204` already in this library) and the auto-generation is just exposing that declaration.

Here are my thoughts on how to proceed:
1. Apply the current default logic to 200/201/204 (depending on the method of course) if the `description` and/or `content` are missing (not empty, completely undeclared in the annotation). This would effectively merge the generated response for the method and the partially-documented response in the annotation.
2. An empty `@ApiResponse` would continue to generate an empty `default` entry. I think the default entry is a special case that should be left completely in the hands of the application developer.
3. Do not generate additional responses other those those specified by the application unless none have been specified at all. We could allow an empty `@ApiResponses` on the method as a way to turn off generation of the default 200/201/204. This is a "no change" item also, except for possibly handling the empty wrapper annotation.

This would make @cghislai's examples "a" - "d" (the first "d") and @neon-dev's examples "h" & "i" work as expected above. Note that we would allow the missing `description` in the output for non-default status codes. If example "i" were a `void` method, the description would be present. If an application includes annotations for responses other than the default 200/201/204, that default would not generate - it must match (or have no responses at all) for that to work.

Thoughts? @EricWittmann and @msavy - this thread has grown quite a bit. I'm curious on your thoughts as well.

**Comment by neon-dev** [comment]
This sounds very reasonable. I just omitted the `204` descriptions for the example. Regardless of the specification, it always makes sense to define a description when there is no self explanatory content.

Just one thing is unclear to me:
Will responseCode "200" with content become the new auto generated response info if no annotations are present? Because I agree that "default" should be the "if-nothing-else-applies" info and should certainly be manually defined.

**Comment by MikeEdgar** [comment]
"200" would be used for non-void methods, and 201/204 would be used for void methods, depending on the HTTP method the Java method is annotated with. This part is unchanged from current behavior.

**Comment by EricWittmann** [comment]
So I've been reading this and trying to wrap my head around everything.  I'll try to describe my understanding of the various issues (in no particular order) here.  :)

The easy one is missing descriptions on auto-generated responses (with no annotations present).  I agree that we should add some simple description so that the generated output is actually valid.

The hard part is how to combine annotations with auto-generated responses (from the method signature).  So first, let's document what should happen without any annotations present:

* `@GET` method that is **non-null** :: `200`
* `@GET` method that is **null** :: ??? (nonsensical but maybe`204`?)
* `@PUT` or `@POST` method that is **null** :: `201`
* `@PUT` or `@POST` method that is **non-null** :: ??? (either `200` or `201`)
* `@DELETE` method that is **non-null** :: ??? (likely `200`)
* `@DELETE` method that is **null** :: `204`

Let's focus on those for now, although there are obviously a bunch of other HTTP methods to cover.  We can document them all later.

So, the question is how to provide additional OpenAPI information to these automatically generated responses.  The developer might want to do any of the following:

* Augment a response with additional info (e.g. `description`)
* Add a response that was not generated at all
* Override an auto-generated response completely

Adding responses is easy - just add an annotation with a `responseCode` that differs from the one that will be auto-generated.

The trick is how to support both augmenting of a generated response and completely overriding it.

My thought is that if the developer **omits** the `responseCode` from the annotation - that could indicate that the *auto-generated response* should be augmented.  And if the `responseCode` is provided **and it matches** the response code of the auto-generated response, then the entire auto-generated response will be replaced by the contents of the annotation.

**Comment by neon-dev** [comment]
@EricWittmann by "method that is `null`" you mean `void` typed methods?

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html states some things about when to return which status codes.

From what I understand `201` actually means that a resource has been created which can be identified by an URI:
> The action performed by the POST method might not result in a resource that can be identified by a URI. In this case, either 200 (OK) or 204 (No Content) is the appropriate response status, depending on whether or not the response includes an entity that describes the result.
If a resource has been created on the origin server, the response SHOULD be 201 (Created) and contain an entity which describes the status of the request and refers to the new resource, and a Location header (see section 14.30).  

So based on that I would never use `201` because it's hard to know if a method is responsible for creating new accessible resources. So I'd always use `200` for non-`void` methods and 204 for `void` ones. If it doesn't match, the developer needs to specify an annotation with the correct `responseCode`.
<br/>

As for your proposed annotation handling, I see one minor problem: A method with more than one possible responses (like in the initial post, `200` and `204` for example) would have to be annotated like so:
```java
@GET
@ApiResponse
@ApiResponse(responseCode = "204", description = "Something something")
public Something get(int something) { ... }
```
But this would disable auto-generation:
```java
@ApiResponse(responseCode = "200")
@ApiResponse(responseCode = "204", description = "Something something")
```
If I have to define `@ApiResponse`s I want to be able to always explicitly set the response codes. This makes it clear in the code and also ensures that the response code doesn't change automatically due to a dependency update (although unlikely and then the content auto-generation would break instead).
Also an `@ApiResponse` without a defined response code to me looks like the "if-nothing-else-applies" response that we discussed above, but I guess we would have to explicitly set `responseCode = "default"` in the future to define that one anyway.

It's not a big deal but something to think about. Once you start adding a description or something else to the default response, it would be nice to immediately see which response code belongs to it. Because there are cases where you have like 5+ annotations, all with different response codes (mainly error codes) and descriptions and then it could start to matter more.

**Comment by EricWittmann** [comment]
> @EricWittmann by "method that is `null`" you mean `void` typed methods?

Yes I meant **void**.  I can't believe I made that mistake!  I had "null" on my brain from another task I was working on I think.  At least that's going to be my excuse.

I have updated the comment to reflect that intent.

**Comment by EricWittmann** [comment]
Good information about the response codes.  It seems like we're splitting the conversation a bit here - but it's a good discussion.  Perhaps we should break off the "what response code to use when" into another isssue?

As for the auto-generation of response information part, I'm starting to be even more convinced that the current implementation might be the right one after all.  Essentially, we'll do our best to generate appropriate responses, but if you don't like the results then you have to annotate everything the way you want it.

The problem with that is obviously that it can become cumbersome to apply all of the annotations you would need to make the OpenAPI doc accurate (on every JAX-RS method you have).  But perhaps we can make some upstream changes to the annotations to make them easier to use.  For example, we could have an `implementation` property on `@ApiResponse` as a mutually exclusive shortcut for `@Content`.

Another possibility is to allow an `@ApiResponse` without a `responseCode` to be the "common" settings for all other responses (whether declared or auto-generated).  And if you wanted an actual **default** response you'd have to specify that with `responseCode = "default"`.

**Comment by neon-dev** [comment]
An `implementation` property would definitely be very useful for methods where the return type doesn't equal the payload type (`Response` for example). For most cases the whole `@Content` construct is unnecessarily large and complex and specifying an implementation class should suffice. But I think this should probably be a separate issue on the spec level.

The problem which we mainly discussed here, is when the auto-generation does 90% of what we expect but we need to add or change the last 10% of additional info. Rewriting the 90% from scratch is just annoying and kind of redundant (especially because of the deep `@Content` structure I explained above).
The common `@ApiResponse` you're describing I actually wouldn't have a use case for. Because I don't see what they would have in common.
Example:
Current state:
```java
@POST
@APIResponse(responseCode = "200", content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = Pet.class, required = true)), description = "Pet was created or updated successfully. The pet may have updated fields (like the ID if it was a new pet) and is therefore returned.")
@APIResponse(responseCode = "204", description = "Pet with given ID doesn't exist. New pets can be created with a missing or empty ID field.")
@APIResponse(responseCode = "400", description = "Invalid payload (see response body).")
@APIResponse(responseCode = "401", description = "Missing token.")
@APIResponse(responseCode = "403", description = "Invalid token.")
@APIResponse(responseCode = "500", description = "Server room is on fire.")
public Pet createOrUpdatePet(Pet pet) { ... }
```
Desired state:
```java
@POST
@APIResponse(responseCode = "200", description = "Pet was created or updated successfully. The pet may have updated fields (like the ID if it was a new pet) and is therefore returned.")
@APIResponse(responseCode = "204", description = "Pet with given ID doesn't exist. New pets can be created with a missing or empty ID field.")
@APIResponse(responseCode = "400", description = "Invalid payload (see response body).")
@APIResponse(responseCode = "401", description = "Missing token.")
@APIResponse(responseCode = "403", description = "Invalid token.")
@APIResponse(responseCode = "500", description = "Server room is on fire.")
public Pet createOrUpdatePet(Pet pet) { ... }
```

I understand that achieving the desired state is a bit tricky, but I think it's doable especially since @cghislai added some very helpful points and ideas. So we're on the right track, it'd be unfortunate if you decided that
> the current implementation might be the right one after all

**Comment by EricWittmann** [comment]
I'm not sure that adding a `implementation` is necessarily a separate issue.  My hope in suggesting it was to find a way to keep the rules simple while also making it reasonably easy to re-specify everything in annotations.  So your example could look like this:

```java
@POST
@APIResponse(responseCode = "200", implementation=Pet.class, description = "Pet was created or updated successfully. The pet may have updated fields (like the ID if it was a new pet) and is therefore returned.")
@APIResponse(responseCode = "204", description = "Pet with given ID doesn't exist. New pets can be created with a missing or empty ID field.")
@APIResponse(responseCode = "400", description = "Invalid payload (see response body).")
@APIResponse(responseCode = "401", description = "Missing token.")
@APIResponse(responseCode = "403", description = "Invalid token.")
@APIResponse(responseCode = "500", description = "Server room is on fire.")
public Pet createOrUpdatePet(Pet pet) { ... }
```

I suppose lists/arrays would need to be handled in some way, but you get the idea.  That's pretty close to your desired state!  And it keeps the rules simple:  if you include any `@APIResponse` annotations, then nothing is auto-generated.

That said, I'm not against making things complicated if we can agree on the rules and they are sensible. :)

**Comment by neon-dev** [comment]
Yup, it depends on what we all agree on. Didn't think about lists yet for the `implementation` property, good point. Also this property alone wouldn't suffice if your endpoint or the containing class is annotated with `@Produces` and a mediatype other than wildcard, which mine usually are (-> `application/json`).
So I'm still not sure if this property is ideal for cases like here. If I remember correctly the auto-generation detects and sets the meda type. Once you have to manually set implementation and the media type, you could as well define a proper `content` property.

**Comment by MikeEdgar** [comment]
> As for the auto-generation of response information part, I'm starting to be even more convinced that the current implementation might be the right one after all. Essentially, we'll do our best to generate appropriate responses, but if you don't like the results then you have to annotate everything the way you want it.

This is what I am thinking also - how can the annotation model best complement the current auto-generated response?

The current implementation will auto-generate `200`, `201`, or `204`. As @neon-dev suggested, `201` _may_ be making an assumption that the app is designed according to REST best practices, etc. If we are OK with that current state of the statuses, the next question is how (and when) does that it merged with annotations. 

1. Scan the method's annotations as in the current state.
2. If the application has given an empty `@ApiResponses`, that is how response auto-generation can be suppressed.
3. Otherwise, if there were `@ApiResponse` annotations, perform the auto-generation of the the default response.
    1. Determine the default status code (`200`, `201`, or `204` - or other if necessary). 
    2. If no annotations were present, generate the same output as current state
    3. Otherwise, if the default status code already exists in the annotations, merge the annotation model onto the generated model. This allows the annotation to override the default description.
    4. If the return type of the method is `Response`, generate the status and description, but skip the `content` generation.

The result is that auto-generation functions largely the same as today, but applications have a way to turn it off or customize it and I believe the @neon-dev's "desired state" example would work. The catch is that if you want the auto-generated response, you need to at least declare an `@ApiResponse` with the same `responseCode`. I submitted PR #152 to perhaps better show the concept.

For methods with `void` return type that have a `@Suspended AsyncResponse` argument, we might consider using `200` instead of `204`. Having an `implementation` attribute would be a nice short-cut for opaque JAX-RS response types (including the Resteasy multipart response types) and should play nice with eclipse/microprofile-open-api#363

I think we should avoid the use of an empty `@ApiResponse` to indicate that a response should be generated. `@ApiResponse#responseCode` is one of the few places where a non-blank default value exists in the annotation model. That means `@ApiResponse()` needs to be treated the same as `@ApiResponse(responseCode = "default")`, which is a special case.

**Comment by EricWittmann** [comment]
I think I'm on board with this with one caveat - if I want to provide my own responses via annotations without anything be auto-generated (and merged), what do I do?  Based on your explanation I think I would do this:

```
@POST
@APIResponses
@APIResponse(responseCode = "200", description = "Pet was created or updated successfully. The pet may have updated fields (like the ID if it was a new pet) and is therefore returned.")
@APIResponse(responseCode = "204", description = "Pet with given ID doesn't exist. New pets can be created with a missing or empty ID field.")
@APIResponse(responseCode = "400", description = "Invalid payload (see response body).")
public Pet createOrUpdatePet(Pet pet) { ... }
```

Because that won't compile.  The `@APIResponse` annotation is repeatable, but the `@APIResponses` annotation (which is the container annotation for `@APIResponse`) is not.  So if you try to do the above, you will get a compiler error:

```
The repeatable annotation @APIResponse may not be repeated where its container annotation type @APIResponses is also used directly
```

But perhaps I'm misunderstanding the proposal.

**Comment by MikeEdgar** [comment]
These are a few scenarios with descriptions for illustration.

[*Change in behavior from current*] Suppress all auto-generation. This would be used in the case where an app may be defining the responses entirely elsewhere, e.g. the static file.
```java
@POST
@APIResponses()
public Pet createOrUpdatePet(Pet pet) { ... }
```
[*Existing behavior*] Suppress the auto-generated `200` by providing **all three** elements that would otherwise be generated: `responseCode = "200"`, `content`, and `description`. 
```java
@POST
@APIResponse(responseCode = "200", content = { ... }, description = "Pet was...")
@APIResponse(responseCode = "204", description = "Pet with given ID doesn't exist...")
@APIResponse(responseCode = "400", description = "Invalid payload (see response body).")
public Pet createOrUpdatePet(Pet pet) { ... }
```
[*Existing behavior*] Suppress the auto-generated `200` by providing a set of response codes that does not include `200`.
```java
@POST
@APIResponse(responseCode = "204", description = "Pet with given ID doesn't exist...")
@APIResponse(responseCode = "400", description = "Invalid payload (see response body).")
public Pet createOrUpdatePet(Pet pet) { ... }
```
[*Change in behavior from current*] Opt-in for the default `description` and `content` generation by providing a simple `200` response. This allows the developer to provide some additional status codes, but still benefit from the auto-generation to fill in the gaps for status `200`.
```java
@POST
@APIResponse(responseCode = "200")
@APIResponse(responseCode = "204", description = "Pet with given ID doesn't exist...")
@APIResponse(responseCode = "400", description = "Invalid payload (see response body).")
public Pet createOrUpdatePet(Pet pet) { ... }
```

**Comment by cghislai** [comment]
Wouldn't it make sense to provide an implementation-specific annotation, like `@GenerateApiResponse`, that would allow to explicitely overwrite/amend the generated response?
My concern is that, as pointed by some people already, most mechanism discussed here for overriding are not intuitive at all and looks like some hidden feature most people would hit without any intent.
I was thinking the presence of any @ApiResponse/@ApiResponses would turn off autogeneration, while the presence of @GenerateApiResponse would turn it on. @GenerateApiResponse would contain the same parameters as @ApiResponse, and declared values would overwrite the defaults for the generated response (so specifying @GenerateResponse(responseCode="default") would still generate content/description.

**Comment by MikeEdgar** [comment]
A custom annotation would be OK, but only if we knew that a standardized version is coming in the future (in my opinion). While it might not be the most intuitive approach, we could probably reduce confusion by having documentation prominently posted about how to use it. 

Documentation in general would probably be a pretty big help for this library. There used to be a docs project that perhaps could be brought back and filled in with things like this.

Another approach could be to ALWAYS generate the `content` for an `@ApiResponse` if not specified, regardless of the `responseCode` and allow the application to ignore it by giving its own `content` or even a `ref`. What are everyone's thoughts on that?

**Comment by EricWittmann** [comment]
Thanks for the examples, @MikeEdgar - you've answered my specific question about disabling auto-generation while **also** providing my own responses via annotations.  The answer is that you can't - so in that scenario you have to fully define/override all aspects of the response.  I suppose you could null out certain properties if that's really what you want (i.e. `content`).

I think the custom annotation idea is OK as well - although honestly I'm not sure how much clearer that is.  That said, I do agree that this is going to be a little tricky to use for the edge cases.  One of my goals is for things to work well most of the time.  And I think this latest proposal is the best one at achieving that, so it has my +1.  

I don't think it's right to **always** generate the `content` if not specified.  I think that could go wrong too often e.g. for the `4xx` response types.
