### ISSUE TITLE
Jackson's JsonNode class is being incorrectly rendered in the spec file

### ISSUE THREAD

**Issue by ricardozanini** [smallrye/smallrye-open-api#1048]
Hi!

Given a data structure model like this:

```java
public class ExpressionModelInput implements Model, MapInput, MapInputId, MapOutput, MappableToModel<ExpressionModel> {

    @com.fasterxml.jackson.annotation.JsonProperty(value = "workflowdata")
    @javax.validation.Valid()
    private com.fasterxml.jackson.databind.JsonNode workflowdata;

    public com.fasterxml.jackson.databind.JsonNode getWorkflowdata() {
        return workflowdata;
    }

    public void setWorkflowdata(com.fasterxml.jackson.databind.JsonNode workflowdata) {
        this.workflowdata = workflowdata;
    }

    @Override()
    public ExpressionModel toModel() {
        ExpressionModel result = new ExpressionModel();
        result.setWorkflowdata(getWorkflowdata());
        return result;
    }
}
```

The final generated file would render the `JsonNode` type like this:

```yaml
components:
  schemas:
    JsonNode:
      type: array
```

That would cause an error in the parsers:

```
Semantic error at components.schemas.JsonNode
Schemas with 'type: array' require a sibling 'items: ' field.
```

I guess it's because `JsonNode` implements `TreeNode` and `Iterable,` the engine understands it as an array. However, we lack the `items` properties, which should be yet another `JsonNode` type.

**Comment by MikeEdgar** [comment]
Interesting, I would have expected the `Iterable<JsonNode>` to do exactly that. I'll take a look and see where it's going wrong.

**Comment by ricardozanini** [comment]
Many thanks, @MikeEdgar!

**Comment by MikeEdgar** [comment]
@ricardozanini - I looked at this a bit and of course it's a bit more complicated beneath the surface. If we introspect `JsonNode`, it will generate all of its properties, none of which would be helpful (i.e. several `boolean` properties for all of the `is*` methods). This may be a case where a `@Schema(implementation = SomeBean.class)` could be used to influence the schema for the `workflowdata` property.

I think the below is what we both expected would be generated, but I'm not sure it really is a useful schema. Particularly because a `JsonNode` in many cases is not actually an `array`, but rather an `object` or some other value type.
```yaml
components:
  schemas:
    JsonNode:
      type: array
      items:
        $ref: #/components/schemas/JsonNode
```

**Comment by ricardozanini** [comment]
> 

Hi @MikeEdgar! Thanks for your insights. I agree that a regular JSON Object should represent the `JsonNode`. So the `@Shema(implementation = JsonObject.class)` would do the work? Being the `JsonObject` the general representation of the JSON object rather than Jackson's Json Node itself. wdyt?

**Comment by msmiths** [comment]
@MikeEdgar The `JsonNode` class is actually the base class for all JSON node types in the Jackson data model. This includes the `ContainerNode` types, `ArrayNode` and `ObjectNode`, as well as all of the `ValueNode` types. Defining a property of type `JsonNode` in a model class that is returned by a REST API is equivalent to saying that it can be of any type... effectively a schema of:

```
{}
```

... or, at the very least:

```
{
    "type": ["number", "string", "boolean", "null", "object", "array"]
}
```

Since the OpenAPI v3 specification modifies the definition of the `type` property taken from the JSON Schema definition, I would suggest that trying to come up with a suitable way of serialising the `JsonNode` type into OpenAPI YAML is fruitless.

The relevant statement in the OpenAPI v3 specification is as follows:

```
type - Value MUST be a string. Multiple types via an array are not supported.
```

**Comment by MikeEdgar** [comment]
@msmiths - 100% agree with you. While it may be used in code for ease, it's too broad to use as the basis for a schema in the API definition.

**Comment by ricardozanini** [comment]
@msmiths @MikeEdgar, we have an edge case in which we need the `JsonNode` being the input model for the REST resources. We are going to fix it by making the interface being interpreted as a generic JSON Object: `{}`.
