### ISSUE TITLE
Standalone `@Parameter` annotation and warning logs

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#1264]
@lthasle , this issue is to further discuss and understand your requirements for using a "detached" `@Parameter` annotation. How do you access the header that is being documented? Are you using the JAX-RS `HttpHeaders` object or something else where there is no matching JAX-RS parameter?

See for original issue https://github.com/quarkusio/quarkus/issues/28006
Relates to changes made in #1197

**Comment by lthasle** [comment]
@MikeEdgar 
The header is accessed with an interreceptor, we get the header via the HttpServerRequest.

The main point with using @Parameter annotation is for swagger.
It will be shown there as a mandatory parameter and the user must include a value.

**Comment by MikeEdgar** [comment]
@lthasle, how many different paths/operations do you add the `@Parameter` annotation to? Would it be an option to provide an `OASFilter` implementation that adds it after the scanner completes? I'm thinking that if you need it for all operations (or most) that may be a cleaner approach than using annotations.

**Comment by lthasle** [comment]
@MikeEdgar 
Thanks for your proposal, I will look into that.
I don't want it on all operations, and I am not sure if I can access the operation name.

**Comment by bboyz269** [comment]
In my case, all requests require tenant id header, which is handled by authentication (multitenancy).  
Since openapi doesn't support putting common params in all endpoints, I had to put `@Paremeter(name = 'X-TENANT-ID', in = HEADER, required = true)` everywhere in order for it to show up on the swagger doc.
I think it's more likely that `@Parameter` annotation is being used for documentation rather than being missing / unused.
