### ISSUE TITLE
Expand parameter scanning beyond resource method arguments

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#129]
The list below is the full set of locations where we might find applicable parameter annotations to scan. The current implementation covers the first possibility.

Possible locations of `@Parameter` and JAX-RS parameter annotations
1) Resource method arguments
2) Resource method (`@Parameter` only)
3) Resource class fields and bean property methods (setters)
4) Fields and bean property methods of `@BeanParam` objects in locations 1 and 3.
5) Support for `@FormParam` annotation by generating a wrapper requestBody/schema (relates to #123)

It's not clear in the MP OpenAPI spec whether `@Parameter` should be supported on resource class fields and bean properties. It seems reasonable to support them wherever JAX-RS parameter annotations can be found, but that may be debatable.

**Comment by EricWittmann** [comment]
In general I definitely think we should try to support as much of JAX-RS as possible.  The MP+OAI spec is pretty much deliberately vague on how implementations should scan for annotations because it's a pretty complicated area and there are many ways to do it.  

I really love that this project is getting this level of attention - the first release was definitely intended to be a starting point, and really covered only the most common JAX-RS use cases.  Increasing coverage is fantastic.

**Comment by MikeEdgar** [comment]
> I really love that this project is getting this level of attention - the first release was definitely intended to be a starting point, and really covered only the most common JAX-RS use cases. Increasing coverage is fantastic.

This is definitely an interesting project and I'm having a great time contributing :-) I think MP+OAI has a lot of potential, both standardized and as extensions.

**Comment by EricWittmann** [comment]
Pretty soon we're going to be bootstrapping a new SmallRye project that does the same thing but with AsyncAPI.  In case that's interesting. :)

**Comment by MikeEdgar** [comment]
Relates to eclipse/microprofile-open-api#357.
