### ISSUE TITLE
@NotNull should lead to "required" in a data structure

### ISSUE THREAD

**Issue by michael-schnell** [smallrye/smallrye-open-api#131]
Using a @NotNull annotation in a data structure should create a "required" entry in the open api structure, but it currently does not.

Example
```java
public class MyCommand {
    @NotNull
    @JsonbProperty("date")
    private LocalDate date;
    @Nullable
    @JsonbProperty("reason")
    private String reason;
}
```
Should have "required" array entry:
```yaml
MyCommand:
  type: object
  required:
    - date
  properties:
    date:
      $ref: '#/components/schemas/LocalDate'
    reason:
      type: string
```
But currently is:
```yaml
MyCommand:
  type: object
  properties:
    date:
      $ref: '#/components/schemas/LocalDate'
    reason:
      type: string
```

**Comment by MikeEdgar** [comment]
I stayed away from implementing `@NotNull` as equal to `required` in the OpenAPI scanner due to the distinction between `nullable` and `required` in the Schema interface. My reasoning was that since the MP API makes a distinction, it might be going too far to interpret `@NotNull` as both `"nullable": false` and `required`. In bean validation there is a single concept (not nullable == required), but in OpenAPI the two seem separate. That is, an API consumer could provide a `date` value of `null`, which meets the requirement that the field is sent.

I know it's not the answer you want, but did you try annotating `MyCommand` with `@Schema(requiredProperties = {...})` ?

**Comment by MikeEdgar** [comment]
This is from OAI data types: https://swagger.io/docs/specification/data-models/data-types/#null

> In objects, a nullable property is not the same as an optional property, but some tools may choose to map an optional property to the null value.

**Comment by michael-schnell** [comment]
OK, was just looking at it from a Java perspective. As you said there @NotNull means actually the same as "required". Maybe it could be done using a new configuration property? I use @NotNull and @Nullable for almost all public API and it would be nice to avoid additional @Schema annotations at parameters and on objects.

**Comment by EricWittmann** [comment]
It seems to me that the JAX-RS annotation scanner should try to produce an OpenAPI document that captures the behavior of the JAX-RS app as best it can.  If `@NotNull` in JAX-RS means both `nullable: false` **and** `required: true` then it might be reasonable to generate that in OpenAPI.  Thoughts?

**Comment by MikeEdgar** [comment]
I agree, and I think that should be the default, but something that can be overridden using `@Schema`.

**Comment by msavy** [comment]
Sounds a reasonable approach to me
