### ISSUE TITLE
microprofile Schema annotation on LocalDateTime fields changes type definition in generated openapi spec

### ISSUE THREAD

**Issue by lyngze** [smallrye/smallrye-open-api#1549]
We utilize smallrye in a small quarkus application. We have Schema annotations on properties in our model classes.
When used on a LocalDateTime property the generated openapi spec changes compared to not having the Schema annotation.

The results are as follows
With Schema annotation:
```
snapshotTimestamp:
  description: Tidspunkt fra RIS for den specifikke kørsel
  type: string
  allOf:
  - $ref: '#/components/schemas/LocalDateTime'
```

Without schema annotations:
```
snapshotTimestamp:
    $ref: '#/components/schemas/LocalDateTime'
```

In both cases the refered LocalDateTime definition is as follows
```
LocalDateTime:
    format: date-time
    type: string
    example: 2022-03-10T12:15:50
```

Version of smallrye reported by gradle dependencies is 
|    +--- io.quarkus:quarkus-smallrye-openapi:3.2.3.Final (c)

**Comment by MikeEdgar** [comment]
Hi @lyngze , what is your expected output? I would consider both results, with or without the annotation, to be correct, but I understand they may not be what you want.

**Comment by jskov-jyskebank-dk** [comment]
This is on me.

This happens when using @Scheme for a description. And it is apparently correct.

My generator did not like it, so I played around with the resource having the annotations a little.

And found that when using @Schema to express a required property, the output is using the allOf-variant.
But when using @JsonProperty for the same, the property keeps the simple $ref-variant.

This threw me for a loop, and I assumed a general problem.


What it really is, probably, is just me not having seen a (string) primitive being expressed with additional attributes before.

Apologies to all for spending time on it.

**Comment by lyngze** [comment]
Yes. After talking about this and consulting the specs it seems to not be an issue with the generated spec but with the generator. We'll close the issue for now and get our generator to generate correct output from this spec variant as well.
