### ISSUE TITLE
@Extension annotations are not processed when declared on fields.

### ISSUE THREAD

**Issue by petrenyi-mark** [smallrye/smallrye-open-api#267]
Hi,

It seems that the microprofile-openapi `@Extension` annotation is only processed if its on the Resource class or on a jax-rs method, but skipped if its on an object (placed on the class or on a field), so in these cases the defined extension is not present in the openapi.yml model.

I created an example in the tck project (in ExtensionsTest: https://github.com/petrenyi-mark/smallrye-open-api/commit/85eea7ed3265bf31ad666900ed31def59b4b29a0)

**Comment by MikeEdgar** [comment]
The fix here depends on whether eclipse/microprofile-open-api#387 is completed for 2.0 I think. If it is part of 2.0, `@Extension` would only be usable as a nested annotation of another extensible annotation - e.g. `@Schema`. If we want to support `@Extension` being placed on additional fields/methods, that should probably go into the `1.x` branch. @EricWittmann, is that your thinking as well?

**Comment by EricWittmann** [comment]
Yeah I think this is something to address after https://github.com/eclipse/microprofile-open-api/issues/387 is done.

@petrenyi-mark to summarize this, we're planning on changing `@Extension` so that it can only be added as a child of some other OpenAPI annotation (e.g. `@Schema`).  The reason is that `@Extension` can be ambiguous when applied to certain fields/methods.  Ambiguity is removed if it's a child of another annotation.  So for your use-case I think we would support something like this:

```java
public class MyBean {
    private String property1;
    @Schema(extensions={@Extension(name="x-minDate", value="2016-01-01")})
    private String property2;
    private String property3;
}
```

Slightly less convenient obviously...but it addresses some other problems.

@MikeEdgar @phillip-kruger  This perhaps goes to our discussion around pluggable processors - it would be nice perhaps for applications to be able to hook into the scanning and supply their own annotations.  That might be tricky in Quarkus since processing is done at build time... or maybe not. :)

**Comment by phillip-kruger** [comment]
Yea I am not sure yet. I am hoping the POC will give us more clarity. I'll keep that in mind when doing the POC. We need users to be able to provide their own annotation set & we need to test run the POC with Quarkus.

**Comment by petrenyi-mark** [comment]
Thanks for the answers we're looking forward to the change :)

**Comment by osbeorn** [comment]
Are there any workarounds to use until this gets changed/fixed?

**Comment by MikeEdgar** [comment]
@osbeorn - you may be able to use an `OASFilter` to add in the extensions where they are needed.

What annotation(s) are you using `@Extension` with? `@Schema`, `@Parameter`, etc.?

**Comment by osbeorn** [comment]
I'm trying to use `@Extension` with `@Schema` on class properties. Will try using the `OASFilter`to augment the schema definition.
Thanks!
