### ISSUE TITLE
Support annotations on setters in addition to fields

### ISSUE THREAD

**Issue by EricWittmann** [smallrye/smallrye-open-api#285]
Originally from here:  https://github.com/quarkusio/quarkus/issues/8415

> OpenAPI Generated documentation for @BeanParam does not reflect the information coded in an @Parameter annotation if you are using a setter.
> 
> It appears that you must annotate a member variable instead of a setter method with Both @QueryParam and @Parameter in order for the API Doc to work properly. However, in our case, we are setting the value into a delegate and this workaround will not work for us.

I haven't confirmed this in SmallRye OpenAPI yet, but it seems likely to be an issue here.

**Comment by MikeEdgar** [comment]
Yes, this is supposed to work. Reading the upstream issue in Quarkus, my best guess is that the `@Parameter` is missing the explicitly required fields called out in the JavaDoc (`name` and `in`) and it may be discarded. Earlier versions of SmallRye were more lenient on the requirement of those annotation properties, but it did cause issues (I forget what they were). It might be manageable to support those properties being omitted in this case since both annotations have the exact same target.

**Comment by MikeEdgar** [comment]
It turns out that the scanner supports leaving out the `name` and `in` properties on the `@Parameter` annotation if there is another JAX-RS annotation on the same target and the target is not a method. I do not recall why it was coded that way and removing the requirement does not break any of the tests. I'll look at removing the limitation this week.
