### ISSUE TITLE
Package deep scan logic changed since 1.1.3

### ISSUE THREAD

**Issue by cen1** [smallrye/smallrye-open-api#289]
I noticed there is a change how packages are scanned after upgrading from v1.1.3 to v1.2.1. 

1.1.3 would also scan all subpackages while 1.2.1 does not. I haven't found it in the release notes or closed issues, I am not sure which behaviour is correct, whether it is a bugfix or regression so I am raising the issue. I did not bisect the commits to find out exactly which version introduced the change.

**Comment by MikeEdgar** [comment]
Hi @cen1 - can you provide a few details about your application? Are you using config properties to limit which packages are being scanned? Also, which runtime environment are you using? Thorntail, Quarkus, etc.?

**Comment by cen1** [comment]
Correct, limiting package scan with config: `OpenApiConfig.scanPackages`. It is programatically set inside the framework extension. I bumped the version on kumuluzee-openapi-mp and noticed the behaviour in one of the sample projects.

**Comment by MikeEdgar** [comment]
@cen1 , please provide a link to the sample project you referenced. Also, please describe the behavior that used to occur and what is happening now.

**Comment by cen1** [comment]
Project: https://github.com/cen1/sample-kumuluzee-openapi-mp

Steps:

1. Testing v1.2.1
```
git clone git@github.com:cen1/sample-kumuluzee-openapi-mp.git
cd sample-kumuluzee-openapi-mp
# in pom.xml modify <smallrye-open-api.version>to 1.2.1
mvn package
java -cp target/classes:target/dependency/* com.kumuluz.ee.EeApplication
curl localhost:8080/openapi?format=json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Generated API",
    "version" : "1.0"
  },
  "paths" : { }
}
```
2. v1.1.3
```
# in pom.xml modify <smallrye-open-api.version>to 1.1.3
mvn clean package
java -cp target/classes:target/dependency/* com.kumuluz.ee.EeApplication
curl localhost:8080/openapi?format=json
# full api spec returned
```

Packages for scan are configured in `src/main/respource/config.yaml`. Configured by extension with `OpenApiConfig.scanPackages`.

**Comment by EricWittmann** [comment]
I haven't tested this lately, but originally (in Thorntail) we were scanning not only the main application deployment, but also all of its "modules" (dependency JARs).  This was critical for e.g. multi-module deployments, where JAX-RS classes might live in some JAR that is not the main deployment.

Ultimately I think SmallRye OpenAPI is pretty much dependent on the Jandex index.  We should be scanning whatever is in there.  I know at one point Thorntail changed the behavior so that the Jandex index given to SmallRye OpenAPI only contained the classes from the main deployment and stopped including the dependencies.

This is the first I'm hearing about Kumuluzee.  It looks cool and I'm happy to see another Microprofile compliant platform (and happy it's using SmallRye).  That said, and @MikeEdgar correct me if my understand of this is stale, it's up to Kumuluzee to provide a Jandex index containing all of the right stuff, including dependencies.  SmallRye will only scan the stuff it knows about.

**Comment by MikeEdgar** [comment]
@EricWittmann, @cen1 , beyond the index, SmallRye also filters with the `FilteredIndexView`. I think the change in behavior being reported was likely introduced with commit 3c06c0df6286a283d8f7b6e8f71d471d88dad8ad. Looking at the spec, it is silent on whether packages configured with `mp.openapi.scan.packages` should be "deep" scanned or not. That may be worth adding a clarification on in the spec before making another change here.

**Comment by EricWittmann** [comment]
Ah ok - I misunderstood what was going on here (reading for comprehension failure).  Now I get it.  Please disregard my comment about Jandex!  :)

I agree that a clarification in the spec seems warranted.  As a developer I would probably expect deep scanning... with the ability to exclude sub-packages if I wanted.
