### ISSUE TITLE
Add support for Mutiny types

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-open-api#310]
It would be good to have OOTB support for `Uni` and `Multi` types from Mutiny.

See https://github.com/quarkusio/quarkus/issues/8811

**Comment by phillip-kruger** [comment]
Sounds good.

**Comment by kenfinnigan** [comment]
As part of this I'm wondering if the `Type` resolution should be removed from `AnnotationScannerExtension` into its own extension/service lookup as there could be the desire to register many types outside an extension that does parsing.

Thoughts @phillip-kruger @EricWittmann @MikeEdgar @ebullient

**Comment by kenfinnigan** [comment]
I'm also curious why the schema registration process for a Class vs a Type of a parameterized type is different.

A class type calls `instrospectClassToSchema` -> https://github.com/smallrye/smallrye-open-api/blob/master/core/src/main/java/io/smallrye/openapi/runtime/io/schema/SchemaFactory.java#L372

But a parameterized type calls `schemaRegistration` -> https://github.com/smallrye/smallrye-open-api/blob/master/core/src/main/java/io/smallrye/openapi/runtime/io/schema/SchemaFactory.java#L377

The internals of each has slightly different semantics, whereas I would've expected them to be identical as at that point they're both dealing with a type.

Is there a reason for the difference?

**Comment by kenfinnigan** [comment]
Also curious as to whether Async type resolution is actually always an async type -> https://github.com/smallrye/smallrye-open-api/blob/master/core/src/main/java/io/smallrye/openapi/runtime/io/schema/SchemaFactory.java#L375

As it's a final `else`, it's more of a catchall. Is there a possibility of a type not being async and reaching this point?

**Comment by MikeEdgar** [comment]
@kenfinnigan , that [final `else` in `SchemaFactory#typeToSchema`](https://github.com/smallrye/smallrye-open-api/blob/26f7b8068fff6f1e87f6f69c393441f7185ea2fa/core/src/main/java/io/smallrye/openapi/runtime/io/schema/SchemaFactory.java#L375) could handle any parameterized type, including generic collections. The async code is there only for the special case where the wrapper is discarded in favor of the type parameter. Originally, the async code was located in the main `OpenApiAnnotationScanner` and was moved to the factory which is why there is duplication to some degree. The type/schema code is due for some refactoring.

As far as registering types, there is a `CustomSchemaRegistry` currently that allows applications to register types directly in the `SchemaRegistry` and also (as of 2.0) a standard configuration prefix `mp.openapi.schema.` that allows for fully-qualified class names to be associated with a schema. `AnnotationScannerExtension` is a special case intended for vendors and I believe exclusively used by Quarkus. 

The `AnnotationScannerExtension#resolveAsyncType` method could probably be renamed to `unwrapType` or something less specific as it would work for `Uni`. The simplest approach for `Multi` would be to do what @EricWittmann did for `Iterable` in e2bcae3c2436c4d2a816774eb847f8eb5fe5229c.

Depending on the demand for this change downstream, that needs to be weighed against the time to re-factor. It might be wise to implement in the quick way on the `1.x` branch for downstream to get results and save any potential re-factoring for `2.0`.

**Comment by kenfinnigan** [comment]
@phillip-kruger @MikeEdgar @EricWittmann Do any of you happen to know offhand whether current master would work with MP OpenAPI 1.1?

I just realized that the master is on the 2.0 SNAPSHOT, which precludes releasing it any time soon.

**Comment by phillip-kruger** [comment]
I think there is breaking changes. @MikeEdgar will know :)

**Comment by kenfinnigan** [comment]
Ok, will make changes in 1.x branch in that case

**Comment by MikeEdgar** [comment]
There are breaking changes master. 1.x is the way to go for near term
