### ISSUE TITLE
Quarkus Swagger UI behind an Ingress Controller

### ISSUE THREAD

**Issue by sirAlexander** [smallrye/smallrye-open-api#381]
I'm having a similar Issue as described here. Has this been fixed yet? if not any ETA, thanks.

https://gitmemory.com/issue/quarkusio/quarkus/4200/535037694

also raised the issue here as not sure of correct place for it.

https://github.com/quarkusio/quarkus/issues/10112

**Comment by MikeEdgar** [comment]
@sirAlexander , it sounds like the OpenAPI document exposed would need to have the public context path appended to each operation. Have you looked at implementing an `OASFilter` (the `filterOpenAPI` method in particular)? That would allow you to change the model before the OpenAPI result is generated. For example, you could iterate over the `openAPI.getPaths` list and update each `PathItem`. Note that you would need to *replace* the path items, since the path string is a map key.

**Comment by sirAlexander** [comment]
@MikeEdgar Thanks for responding. Thing is all other extensions work as expected with the Ingress setup. i.e. path /health  /metrics even /openapi etc..  It's just the /swagger-ui path that doesn't.

As the set-up above is a common production setup, i'd expect the `open api' to behave just like all the other quarkus extensions, without "end-users" having to implement specific code to get it in line.

**Comment by phillip-kruger** [comment]
So the `/openapi` url works ? It's just that `/swagger-ui` does not ? Can you actually make a REST call ? (using curl for example).
And what does not work in the swagger-ui ? What error do you get ?

**Comment by phillip-kruger** [comment]
If the above is the case (openapi works but swagger ui not) we can close this issue and handle this in https://github.com/quarkusio/quarkus/issues/10112.

(As SmallRye OpenAPI has got nothing to do with Swagger UI in Quarkus.)

**Comment by sirAlexander** [comment]
@phillip-kruger openapi works but not swagger-ui so i guess we close this and handle it in quarkusio/quarkus#10112.
Thanks
