### ISSUE TITLE
2.0.x releases are missing from maven central

### ISSUE THREAD

**Issue by pferraro** [smallrye/smallrye-open-api#400]
The latest release I can find is 1.2.4.

**Comment by MikeEdgar** [comment]
@pferraro - which group/artifact are you searching under?

https://search.maven.org/artifact/io.smallrye/smallrye-open-api

**Comment by jmini** [comment]
I think the was a changed made with `2.0.0`.

```xml
<dependency>
  <groupId>io.smallrye</groupId>
  <artifactId>smallrye-open-api</artifactId>
  <version>1.2.4</version>
</dependency>
```
Used to be be `jar` packaging, but since `2.0.x` it has the `pom` packaging:

https://github.com/smallrye/smallrye-open-api/blob/5a9620d0607db834da2f269be9ae33347bccb8b6/implementation/pom.xml#L11-L12

Probably this is due to the refactoring made for spring support.

I am not an expert in this area (probably @MikeEdgar can tell if I am right or not), but for users that use SmallRye independently of an app server (Wildfly, Quarkus, …) which tend to provide the implementation based on the API used (not sure if this is entirely true). If they are building their app on to of `Jakarta RESTful Web Services` (a.k.a `JAX RS`) now need to use following dependency instead of the previous one:

```xml
<dependency>
  <groupId>io.smallrye</groupId>
  <artifactId>smallrye-open-api-jaxrs</artifactId>
  <version>2.0.3</version>
</dependency>
```

**Comment by phillip-kruger** [comment]
Yes @jmini is 100% correct. From V2 you can now use the jaxrs artifact as specified. You can also use the spring one to add openapi support for spring-web. That is already used in Quarkus. Closing this, please reopen if you have any issues.

**Comment by pferraro** [comment]
Aha! Thanks for the clarification!
