### ISSUE TITLE
Allow scanning in interfaces in separate module

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-open-api#449]
Allow the creation of schema when the annotations are in a seperate module in an interface:

From https://github.com/smallrye/smallrye-open-api/pull/445:

"But the OpenAPI generation still needs an application class for the JAX-RS annotations to get scanned. If I only have an interface with JAX-RS annotations (implementation is in another module), the OpenAPI documentation is basically empty.

You can find a small reproducer project here: https://github.com/jglink/openapi-doc-from-interface
The project only has 1 interface class (my.project.api.SomeApi) with a JAX-RS annotation and so the generated openapi.yaml only defines some basic stuff.

All the OpenAPI annotations (like @Operation, @APIResponse) are on the interface. So I´d expect that it´s possible to generate the documentation out of it"

**Comment by msmiths** [comment]
@phillip-kruger While I agree that it should be possible to generate the OpenAPI document when the relevant annotations are specified on an interface, I believe that there must be a class that implements the interface.  The example provided only includes the interface.

There is a more complete example of this approach in the book **RESTful Java with JAX-RS 2.0** by Bill Burke, specifically the **JAX-RS and Java Interfaces** section in Chapter 3.

**Comment by jglink** [comment]
@msmiths you´re right. My example only contains the interface because that´s how we organized our project.
The _API_ module of a project only has the interfaces with the JAX-RS annotations defined and of course some POJOs for the parameters/responses.

The implementation of the interface is in a separate module.
But we would have the possibility to create the OpenAPI documentation just out of the interface. In the end, that´s the place where it´s defined.

**Comment by msmiths** [comment]
@jglink I am not disagreeing... I just want to ensure that we do not generate content in the OpenAPI document for interfaces that have no implementation in the application. Hopefully this is unlikely... but still possible.

**Comment by phillip-kruger** [comment]
There is no way to know, while scanning a module with some interfaces, if there are an implementation. But I think we can still look into doing this, as it would be up to the developer to make sure there is a implementation. Without one, there will be no endpoint so noting will work anyway. I'll look into this and see what the effort is.

**Comment by MikeEdgar** [comment]
@phillip-kruger , FYI is code that explicitly excludes interfaces without an implementation. 

`io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.getJaxRsResourceClasses(IndexView)`

**Comment by phillip-kruger** [comment]
Thanks @MikeEdgar . Maybe we should "switch on" this feature via config ? Default the current behaviour ?  w.d.y.t ?

**Comment by MikeEdgar** [comment]
Looking through those older issues, I think the idea was to avoid interfaces used as REST clients and there is something in the spec about that: https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#61-microprofile-rest-client. In light of that, I think the implementation should change to only apply that exclusion if the interface has `@RegisterRestClient`. That should avoid the need for a new config. There is actually a TCK test for that scenario and the only reason SR passes it is because there is no implementation, not because of the annotation.

**Comment by phillip-kruger** [comment]
That sounds like a plan. Thanks @MikeEdgar !

**Comment by jglink** [comment]
@MikeEdgar In our case, it´s the complete opposite.
We do have an API module which contains interface that define the REST API and the interfaces do contain the @RegisterRestClient annotation.
The API module is used in two ways:
- by a so-called _service_ module which implements the interfaces
- by other projects _service_ module to actually call the service(s)

As we have the API module only defining the REST interfaces (and some POJOs for request parameters and responses) it would be ok (and actually wanted ) to create to create the OpenAPI doc for it, despite the linked spec topic.

Is there a way that we could parameterize if @RegisterRestClient annotated classes should be filtered or not?
I´d be happy to do the coding if there is a chance that the PR is used.

Thanks

**Comment by MikeEdgar** [comment]
@jglink - I'm not sure how much flexibility we have in that area since it relates to the spec. Would you be willing to have an empty sub-interface in your API module that you use with `@RegisterRestClient` and remove that annotation from the main interface definition? I'm not completely sure this will work, but might be worth a try.

E.g.
```java
@Path("/api/v1")
public interface MyResource {
   // ... resource methods
}

@RegisterRestClient
public interface MyResourceClient extends MyResource {
    // Use this interface to call MyResource from client components, define in either your API or the other service projects
}
```

**Comment by jglink** [comment]
Using a base interface would work for the OpenAPI doc generation.
But as `RegisterRestClient` is not marked with `@Inherited` I think that Quarkus would not know that this interface is meant to be available for CDI injection as a REST Client.

I´ll try to go the way and write/register an own annotation scanner.

Thanks for your quick responses!

**Comment by MikeEdgar** [comment]
Reopening this issue as I think the approach needs to be revisited, see https://github.com/quarkusio/quarkus/issues/14712

**Comment by MikeEdgar** [comment]
@phillip-kruger , @msmiths - what is your take on this? It seems there are users coming at this problem from both sides. 

Just to propose a possible solution for discussion: automatically exclude *all* interfaces without implementations (the old functionality) unless explicitly included by one of the inclusion properties, `mp.openapi.scan.classes` and `mp.openapi.scan.packages`.

I think that allows us to support all scenarios without requiring any changes to the specification.

**Comment by phillip-kruger** [comment]
I agree.

**Comment by msmiths** [comment]
@MikeEdgar Agreed. It sounds like this approach allows @jglink to achieve what he wants while still being compliant with the spec.

**Comment by MikeEdgar** [comment]
Thanks for the feedback - I'll put together a PR for the change in a day or two.
