### ISSUE TITLE
logo.png and style.css on Quarkus not work

### ISSUE THREAD

**Issue by brunohorta82** [smallrye/smallrye-open-api#574]
Hello I try override the quarkus logo with the logo.png inside of folder src/resources/META-INF/branding but seems not work.

I already clean the caches and the problem persists.

**Comment by phillip-kruger** [comment]
See if this example works for you : https://github.com/phillip-kruger/openapi-example

Also see this issue: https://github.com/quarkusio/quarkus/issues/13627 - especially this comment "It turned out it was my configuration of Quarkus-maven-plugin that was only executing build phase and apparently that cause the issue." - maybe you have the same issue ?

**Comment by phillip-kruger** [comment]
@brunohorta82 - Any feedback ?

**Comment by phillip-kruger** [comment]
Closing. No feedback. Please reopen if you believe this is still an issue
