### ISSUE TITLE
2.0 Negative Test Coverage for API/SPI Changes

### ISSUE THREAD

**Issue by scottcurtis2605** [smallrye/smallrye-open-api#621]
As per the listed [API/SPI changes in 2.0](https://download.eclipse.org/microprofile/microprofile-open-api-2.0-RC3/microprofile-openapi-spec.html#_apispi_changes), I was unable to identify unit tests within the codebase which examine & verify expected behaviour within the following negative scenarios:

`@SchemaProperty`:
- Implementation class also specified with conflicting properties/values (ensure `@SchemaProperty` values override implementation class)
- Testing scenarios with malformed properties (e.g. malformed properties such as name or value, if these exist)

`@RequestBodySchema`:
- Reference non-existent class
- Referenced class does not define a valid schema
- Malformed properties (wrong name, wrong data type)

`@APIResponseSchema`:
- Reference non-existent class
- Referenced class does not define a valid schema
- Malformed properties (wrong name, wrong data type)

`mp.openapi.schema.*` MP Config keys:
- Reference non-existent class
- Referenced class does not define a valid schema
- Malformed properties (wrong name, wrong data type)

MP Config extensions defined by SmallRye for limiting classes/dependencies that are scanned :
- Reference non-existent jar(s)
- Malformed list (not comma-separated, specify URLs, etc.)

I will attempt to implement the following tests, as the behaviour above is required to be examined for Open Liberty's OpenAPI 2.0 release approval.

If I have missed any tests which already examine the following behaviour, please feel free to direct me to those!

**Comment by MikeEdgar** [comment]
Thanks @scottcurtis2605 . Tests for these scenarios would be a great addition. The test that `@SchemaProperty` overrides implementation class attributes also might be a good addition to the TCK in the spec project.

**Comment by Azquelt** [comment]
I looked through this list with Scott, here's what we're going look at:

`@SchemaProperty`
 - test invalid values for each attribute

`@RequestBodySchema` / `@APIResponseSchema` / `@Schema`
 - these are all used to do similar things and reference a class to define a schema
 - is it possible for a referenced class not to define a valid schema or to be invalid in some other way?

`@APIResponseSchema`
 - test invalid description/code (presumably the code must be a number)

`mp.openapi.schema.*`
 - test if a key is defined for a class which does not exist (expect that it would be ignored since we never need to generate a schema for the type)
 - test with a value which is not valid JSON
 - test with a value which is valid JSON but is not a valid schema

MP Config extensions defined by SmallRye for limiting classes/dependencies that are scanned:
 - these appear to be
   - mp.openapi.extensions.smallrye.scan-dependencies.disable
   - mp.openapi.extensions.smallrye.scan-dependencies.jars
 - however, we couldn't see how these are implemented currently in the code. Looking at their purpose, are these config parameters something that an integrator needs to implement themselves since I couldn't see where smallrye-open-api deals with dependencies or jar files? It appears to just expect a Jandex `Index` with all of the classes to scan.

Other notes:
 - we're not sure of the best way to test referencing a class that doesn't exist at runtime or whether this is worth attempting. The class would need to be present at compile time but not when the test is run.
 - is there a straightforward way to assert log messages from unit tests? In some of these cases, I think it would make sense to assert that an error or warning is emitted, even if the invalid value is then ignored.

**Comment by scottcurtis2605** [comment]
PR #644 has been made which implements negative tests for the following behaviour:

> `@APIResponseSchema`
> 
>   -  test invalid description/code (presumably the code must be a number)

**Comment by scottcurtis2605** [comment]
In my most recent PR, I had a question regarding testing the following behaviour:

> `mp.openapi.schema.*`
>    - test with a value which is valid JSON but is not a valid schema

Currently, if specifying an invalid schema via config (e.g. with `name` or `type` misspelt), the resultant document will not be rendered with the misspelt field in question. This is correct behaviour, though I think it should be noted that there is no user-feedback for this - is the current behaviour intended?

**Comment by MikeEdgar** [comment]
@Azquelt , @scottcurtis2605 -

1. I don't think it's really possible for one of the schema annotations to reference an invalid schema. I think the only scenario would be the same as # 3 where the class is missing from the index and is not available for introspection.
2. `mp.openapi.extensions.smallrye.scan-dependencies` - you are correct that these would be used by integrator when creating the `Index`.
3. For the "best way to test referencing a class that doesn't exist at runtime", consider leaving it out of the Jandex index. It should be treated as an opaque object in that case.
4. To check for log messages, there is likely a way to provide an output stream/handler for the logging framework (JBoss logging) and check the output, but I don't know the exact details.

**Comment by Azquelt** [comment]
With #703 in, I think we've done all that we need to here. Integrators should test that they handle invalid values for `mp.openapi.extensions.smallrye.scan-dependencies.*` gracefully if they support them.

**Comment by phillip-kruger** [comment]
Great ! closing !
