### ISSUE TITLE
Incorrect Response Code - DELETE

### ISSUE THREAD

**Issue by scottcurtis2605** [smallrye/smallrye-open-api#642]
When implementing the `@APIResponseSchema` tests as described within #621, the following behaviour was observed: 

When testing that the correct `responseCode` attribute on `@APIResponseSchema` is set in cases when an invalid `responseCode` value is passed to the attribute, a JAX-RS `@DELETE` method with `void` return type, and a JAX-RS `AsyncResponse` parameter, returns a `204` response code. This can be seen [within my fork](https://github.com/scottcurtis2605/smallrye-open-api/blob/4ec855fc724dec556c603d7c4faf01a563126446/extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/ApiResponseTests.java#L183).

According to the [JavaDoc](https://download.eclipse.org/microprofile/microprofile-open-api-2.0/apidocs/), I believe expected response code in this scenario should be `200`:

```
 If no value is specified, a default shall be determined using REST conventions as follows:

- If the method's return type is void and the HTTP method is @POST, the code will be 201.
- Otherwise, if the method's return type is void the method does not list a JAX-RS AsyncResponse parameter, the code will be 204.
- Otherwise, the code will be 200. 
```

Assuming the JavaDoc should read, "Otherwise, if the method's return type is void **_AND_** the method does not list a JAX-RS AsyncResponse parameter, the code will be 204.", I believe the current behaviour displayed by the library is incorrect.

**Comment by MikeEdgar** [comment]
@scottcurtis2605 - I agree that based on the JavaDoc the response should be `200` due to the (1) `void` return type and (2) the presence of and `AsyncResponse` argument. I also agree with your correction to the JavaDoc description.

@phillip-kruger - it looks like the Spring/Vert.x response handling may need to be split from the default/JAX-RS handling. Do either of those frameworks have the equivalent of `AsyncResponse` ?

**Comment by scottcurtis2605** [comment]
Thanks @MikeEdgar!
