### ISSUE TITLE
OpenAPISerializer: siblings value allongside $ref should not be serialized

### ISSUE THREAD

**Issue by jmini** [smallrye/smallrye-open-api#77]
With a spec containing some values defined near to the `ref` attribute, the output of `OpenAPISerializer.serialize(openAPI, OpenAPISerializer.Format.JSON)` serialize those member, producing an invalid spec.

Example :

```java
createOpenAPI()
  .openapi("3.0.1")
  .info(
    createInfo()
      .title("Ping Specification")
      .version("1.0")
  )
  .addServer(
    createServer()
      .url("http://localhost:8000/")
  )
  .paths(
    createPaths()
      .addPathItem(
        "/ping", createPathItem()
          .GET(
            createOperation()
              .operationId("pingGet")
              .responses(
                createAPIResponses()
                  .addAPIResponse(
                    "200", createAPIResponse()
                      .description("OK")
                      .content(
                        createContent()
                          .addMediaType(
                            "application/json", createMediaType()
                              .schema(
                                createSchema()
                                  .ref("#/components/schemas/Hello")
                                  .type(Schema.SchemaType.OBJECT) // Wrong value because "$ref" is present
                                  .description("The hello type") // Wrong value because "$ref" is present
                              )
                          )
                      )
                  )
              )
          )
      )
  )
  .components(
    createComponents()
      .addSchema(
        "Hello", createSchema()
          .type(Schema.SchemaType.OBJECT)
          .addProperty(
            "timestamp", createSchema()
              .type(Schema.SchemaType.INTEGER)
              .description("Unix timestamp (generation time)")
              .format("int32")
          )
          .addProperty(
            "message", createSchema()
              .type(Schema.SchemaType.STRING)
          )
      )
  );
```

Produces:

```json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Ping Specification",
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "http://localhost:8000/"
  } ],
  "paths" : {
    "/ping" : {
      "get" : {
        "operationId" : "pingGet",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Hello",
                  "description" : "The hello type",
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Hello" : {
        "type" : "object",
        "properties" : {
          "timestamp" : {
            "format" : "int32",
            "description" : "Unix timestamp (generation time)",
            "type" : "integer"
          },
          "message" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

In Swagger-Editor (online), I get this error:

> Sibling values are not allowed alongside $refs

In KaiZen-Editor (plugin for Eclipse), I get this error:

> Failed to match exactly one schema:
> - response:
>	Failed to match exactly one schema:
>	 - schema:
>		 - object has properties "$ref" which are not allowed
>	 - reference:
>		 - object has properties "description", "type" which are not allowed
> - reference:
>	 - object has missing required properties "$ref"
>	 - object has properties "content", "description" which are not allowed

Expected would be:
```json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Ping Specification",
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "http://localhost:8000/"
  } ],
  "paths" : {
    "/ping" : {
      "get" : {
        "operationId" : "pingGet",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Hello"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Hello" : {
        "type" : "object",
        "properties" : {
          "timestamp" : {
            "format" : "int32",
            "description" : "Unix timestamp (generation time)",
            "type" : "integer"
          },
          "message" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

In my opinion, even if the model contains incorrect value (near to reference), the serializer should ignore them during JSON/YAML serialization.

What do you think?

**Comment by msavy** [comment]
Interesting. IMO, if it's invalid according to the spec then it should ignore those impermissible fields rather than produce an incorrect output. Unless we want to have a slop mode that allows it? I'm not sure I see that being valuable, though.

Does this only happen in schema `$refs`? 

Happy or this to be assigned to me to fix.

**Comment by jmini** [comment]
No the rule with `$ref` is common to all types implementing `org.eclipse.microprofile.openapi.models.Reference<T>`. If ref is set, then all other members of this object are illegal.

For reference: https://github.com/OAI/OpenAPI-Specification/issues/556

---

I tend also to think that the serializer should ignore them to produce a valid output rather than to output them because they are present in the Object, but this is indeed a matter of taste.

**Comment by msavy** [comment]
Sorry meant whether this error also happened for non-schema examples in our
implementation as I think different code handles that.

**Comment by EricWittmann** [comment]
I don't have a strong preference about this.  So if we want to the serializer to ignore other properties when a `$ref` is present, that's fine.  I would just say that it's not really the serializer's job to ensure that its output is valid.  There are other mutually exclusive properties defined in the specification.  Are we going to have the serializer handle that as well?  Why do we think `$ref` is the property we should keep rather than all the others?  What if the user adds a `$ref` but **also** fully defines an inline schema?  Why not keep the inline schema and drop the ref?

There are also all sorts of invalid things I could do when creating my OpenAPI document.  Many of those are impossible for the serializer to fix.

To me, this seems like a request for an optional validation step, where we actually validate the output and provide a report of some sort.

**Comment by jmini** [comment]
Thank you a lot for your feedback. I was myself not sure about this and I like your vision for the responsibility of the serializer.

I tend to be biased by what I know from other OpenAPI libraries, but we do not need to reproduce here all the mistake they have made.

Feel free to close this issue.

---
**About spec validation:**

I have created https://github.com/eclipse/microprofile-open-api/issues/331 to discuss the opportunity to add a way to report errors and warnings for an existing model.

Then each vendor can implement the set of rules he consider useful.

**Comment by EricWittmann** [comment]
OK the more I think about this the more I think that validation is definitely the responsibility of some other layer.  So I agree that we should close this issue as "will not fix" - but with the caveat that we intend to eventually implement validation of the resulting OpenAPI document so that errors such as the one(s) you point out in this issue will be reported in a sensible way.

If anyone disagrees then we can re-open this issue!
