### ISSUE TITLE
Quarkus internal models should not be exposed in swagger doc

### ISSUE THREAD

**Issue by u6f6o** [smallrye/smallrye-open-api#786]
Assuming we have the following controller: 

```kotlin
@Operation(description = "Returns a user configuration")
@APIResponses(
    APIResponse(responseCode = "200"))
@GET
@Produces(MediaType.USER_CONFIGURATION)
fun getUserConfiguration(): Uni<Response> {
    ...
    return Uni.createFrom().item(Response.ok(userConfigModel).build())
}
```
The library currently also exposes internal model information from the uni and/or response object: 

![image](https://user-images.githubusercontent.com/1176370/115359583-1b133080-a1bf-11eb-9cc2-08f1b5f3f4dc.png)

This can be circumvented by providing an openapi filter
```
mp.openapi.filter=example.OpenApiFilterImpl
```
Yet, imo, these classes should be excluded automatically.

**Comment by phillip-kruger** [comment]
@MikeEdgar - w.d.y.t ? We should be able to ignore Multi and Uni ?

**Comment by MikeEdgar** [comment]
They should already be ignored, or rather handled by unwrapping their generic types. It looks like the issue here is that the `Uni`'s generic type (the JAX-RS `Response`) is being unwrapped and inspected. The result of that should really be an empty object or a response without a schema.

@u6f6o, in your case, the `@APIResponse` annotation should be updated to include the information that is not present in the function's return type. I.e., you need to add `content = @Content(schema = @Schema(implementation = ClassOfUserConfigModel.class))`. The return type of `Uni<Response>` does not contain the information necessary to determine the response's schema so it much be added explicitly.

**Comment by u6f6o** [comment]
works like a charm! Many thanks for the assistance. 👍
